language: elixir

elixir:
  - 1.4
  - 1.3
otp_release:
  - 20.0
  - 19.3
  - 18.3

matrix:
  exclude:
    - elixir: 1.3
      otp_release: 20.0

sudo: false

addons:
  code_climate:
    repo_token: 2120e266d5969f168d56e07cc00c90750fe5dae4b544e0ba20657ac5bd6e077b

script:
  - mix deps.get
  - mix espec

after_script:
  - mix deps.get --only docs
  - MIX_ENV=docs mix inch.report
