language: elixir

elixir:
  - 1.5
  - 1.4
  - 1.3
otp_release:
  - 20.0
  - 19.3
  - 18.3

matrix:
  exclude:
    - elixir: 1.3
      otp_release: 20.0

sudo: false

addons:
  code_climate:
    repo_token: a0279c93071085c527e91c45c5bd604b991a845b1936b7a75ca1f3bc3b45338e

env:
  - MIX_ENV=test

script:
  - mix deps.get
  - mix espec
  - mix coveralls.travis

after_script:
  - mix deps.get --only docs
  - MIX_ENV=docs mix inch.report
